#!/bin/bash
# Quick Testing Script for Template Consistency

echo "========================================="
echo "Template Consistency Testing Guide"
echo "========================================="
echo ""
echo "Step 1: Ensure both services are running"
echo "  - Frontend: http://localhost:5173"
echo "  - Backend: http://localhost:3000"
echo ""
echo "Step 2: Test the Modern Template"
echo ""
echo "  A. Visual Preview Test:"
echo "     1. Go to http://localhost:5173"
echo "     2. Load or create a resume"
echo "     3. Select 'Modern' template"
echo "     4. Check that fonts look clean (Arial/Helvetica, not serif)"
echo "     5. Verify spacing is consistent"
echo ""
echo "  B. Regenerate Test:"
echo "     1. Click 'Regenerate Resume' button"
echo "     2. Check for errors in browser console (F12)"
echo "     3. Verify preview still looks correct"
echo ""
echo "  C. PDF Download Test:"
echo "     1. Click 'Download PDF'"
echo "     2. Open the PDF file"
echo "     3. Compare fonts and spacing with the preview"
echo "     4. Verify it matches the browser view"
echo ""
echo "  D. DOCX Download Test:"
echo "     1. Click 'Download DOCX'"
echo "     2. Open in Word or compatible viewer"
echo "     3. Compare fonts (should be Arial)"
echo "     4. Compare with PDF - should be very similar"
echo ""
echo "Step 3: What to Look For"
echo ""
echo "  Font Consistency:"
echo "    ✓ Preview should use Arial/Helvetica"
echo "    ✓ PDF should use Helvetica"
echo "    ✓ DOCX should use Arial"
echo "    ✓ All should look like sans-serif fonts (no serifs)"
echo ""
echo "  Size Consistency:"
echo "    ✓ Name header: Large and bold (~20pt)"
echo "    ✓ Section headers: Bold and colored (~11pt)"
echo "    ✓ Job titles: Bold (~10pt)"
echo "    ✓ Body text: Regular (~9pt)"
echo "    ✓ Dates/Location: Smaller (~8.5pt)"
echo ""
echo "  Spacing Consistency:"
echo "    ✓ Same gaps between sections"
echo "    ✓ Same gaps between items"
echo "    ✓ Consistent bullet point indentation"
echo ""
echo "========================================="
echo "Testing Notes:"
echo "========================================="
echo ""
echo "Backend Server Status:"
